# Generated by Django 3.2.18 on 2023-05-08 14:06

from django.db import migrations, models
import imagekit.models.fields
import infobases.models


class Migration(migrations.Migration):

    dependencies = [
        ('infobases', '0002_auto_20230427_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=infobases.models.Image.info_image_path),
        ),
    ]
